version: '3.8'

services:
  redis-stack:
    image: redis:latest
    container_name: sentinel-redis
    ports:
      - "6380:6379"
    networks:
      - sentinel-net

  ingestor-app:
    build: .
    container_name: sentinel-ingestor
    ports:
      - "8080:8080"
    depends_on:
      - redis-stack
    environment:
      - SPRING_DATA_REDIS_HOST=redis-stack
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge